literal percent needs to be doubled in format string
The non-doubled percent was causing dalvikexplorer to crash with the
following exception:

FATAL EXCEPTION: main
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at org.jessies.dalvikexplorer.BetterArrayAdapter.createViewFromResource(BetterArrayAdapter.java:201)
	at org.jessies.dalvikexplorer.BetterArrayAdapter.getView(BetterArrayAdapter.java:176)
	at android.widget.AbsListView.obtainView(AbsListView.java:2612)
	at android.widget.ListView.makeAndAddView(ListView.java:1838)
	at android.widget.ListView.fillDown(ListView.java:681)
	at android.widget.ListView.fillSpecific(ListView.java:1339)
	at android.widget.ListView.layoutChildren(ListView.java:1637)
	at android.widget.AbsListView.onLayout(AbsListView.java:2446)
	at android.view.View.layout(View.java:14482)
	at android.view.ViewGroup.layout(ViewGroup.java:4469)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14482)
	at android.view.ViewGroup.layout(ViewGroup.java:4469)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1669)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1527)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at android.view.View.layout(View.java:14482)
	at android.view.ViewGroup.layout(ViewGroup.java:4469)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14482)
	at android.view.ViewGroup.layout(ViewGroup.java:4469)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2151)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1970)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1183)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4863)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
	at android.view.Choreographer.doFrame(Choreographer.java:532)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5329)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at org.jessies.dalvikexplorer.BetterArrayAdapter.createViewFromResource(BetterArrayAdapter.java:198)
	... 37 more
Caused by: java.util.UnknownFormatConversionException: Conversion:
	at java.util.Formatter$FormatSpecifierParser.unknownFormatConversionException(Formatter.java:2304)
	at java.util.Formatter$FormatSpecifierParser.advance(Formatter.java:2298)
	at java.util.Formatter$FormatSpecifierParser.parseConversionType(Formatter.java:2377)
	at java.util.Formatter$FormatSpecifierParser.parseArgumentIndexAndFlags(Formatter.java:2348)
	at java.util.Formatter$FormatSpecifierParser.parseFormatToken(Formatter.java:2281)
	at java.util.Formatter.doFormat(Formatter.java:1069)
	at java.util.Formatter.format(Formatter.java:1040)
	at java.util.Formatter.format(Formatter.java:1009)
	at java.lang.String.format(String.java:1988)
	at org.jessies.dalvikexplorer.SensorItem.toString(SensorItem.java:44)
	at org.jessies.dalvikexplorer.SensorItem.toSubtitle(SensorItem.java:22)
	... 40 more